"""baseline

Revision ID: c1a770f1636e
Revises: 
Create Date: 2026-08-11 15:50:51.582207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a770f1636e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('announcement_dismissals_announcement_id_fkey'), 'announcement_dismissals', type_='foreignkey')
    op.drop_constraint(op.f('announcement_dismissals_user_id_fkey'), 'announcement_dismissals', type_='foreignkey')
    op.create_foreign_key(None, 'announcement_dismissals', 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'announcement_dismissals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interview_contexts_user_id_fkey'), 'interview_contexts', type_='foreignkey')
    op.create_foreign_key(None, 'interview_contexts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('leads_user_id_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('partner_commissions_partner_id_fkey'), 'partner_commissions', type_='foreignkey')
    op.drop_constraint(op.f('partner_commissions_referee_id_fkey'), 'partner_commissions', type_='foreignkey')
    op.create_foreign_key(None, 'partner_commissions', 'users', ['partner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'partner_commissions', 'users', ['referee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('referrals_referrer_id_fkey'), 'referrals', type_='foreignkey')
    op.drop_constraint(op.f('referrals_referee_id_fkey'), 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'users', ['referrer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'users', ['referee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('session_feedback_user_id_fkey'), 'session_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'session_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('usage_daily_user_id_fkey'), 'usage_daily', type_='foreignkey')
    op.create_foreign_key(None, 'usage_daily', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_referred_by_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['referred_by_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('withdrawals_partner_id_fkey'), 'withdrawals', type_='foreignkey')
    op.create_foreign_key(None, 'withdrawals', 'users', ['partner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.create_foreign_key(op.f('withdrawals_partner_id_fkey'), 'withdrawals', 'users', ['partner_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_referred_by_id_fkey'), 'users', 'users', ['referred_by_id'], ['id'])
    op.drop_constraint(None, 'usage_daily', type_='foreignkey')
    op.create_foreign_key(op.f('usage_daily_user_id_fkey'), 'usage_daily', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'session_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('session_feedback_user_id_fkey'), 'session_feedback', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('referrals_referee_id_fkey'), 'referrals', 'users', ['referee_id'], ['id'])
    op.create_foreign_key(op.f('referrals_referrer_id_fkey'), 'referrals', 'users', ['referrer_id'], ['id'])
    op.drop_constraint(None, 'partner_commissions', type_='foreignkey')
    op.drop_constraint(None, 'partner_commissions', type_='foreignkey')
    op.create_foreign_key(op.f('partner_commissions_referee_id_fkey'), 'partner_commissions', 'users', ['referee_id'], ['id'])
    op.create_foreign_key(op.f('partner_commissions_partner_id_fkey'), 'partner_commissions', 'users', ['partner_id'], ['id'])
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_user_id_fkey'), 'leads', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'interview_contexts', type_='foreignkey')
    op.create_foreign_key(op.f('interview_contexts_user_id_fkey'), 'interview_contexts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'announcement_dismissals', type_='foreignkey')
    op.drop_constraint(None, 'announcement_dismissals', type_='foreignkey')
    op.create_foreign_key(op.f('announcement_dismissals_user_id_fkey'), 'announcement_dismissals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('announcement_dismissals_announcement_id_fkey'), 'announcement_dismissals', 'announcements', ['announcement_id'], ['id'])
    # ### end Alembic commands ###
